language: cpp

sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python-numpy
  - sudo apt-get install -y -qq freeglut3 freeglut3-dev libxmu-dev libxi-dev

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - make
  - make 2.cpp.log
  - cat resume.2.cpp.log
  - make 3.cpp.log
  - cat resume.3.cpp.log
  - make 2.openmp.log
  - cat resume.2.openmp.log
  - make 3.openmp.log
  - cat resume.3.openmp.log